### PR TITLE
Fix alternative backend syntax example for DRink!

### PR DESCRIPTION
**Pull request by davidsemakula**
See https://github.com/paritytech/ink/pull/2083

### CODE REVIEW

**Comment by davidsemakula** [comment]
@cmichi Additionally, the example link [here](https://github.com/paritytech/ink-docs/pull/331/files#diff-f108ed3ca9a913da83ecdb04d6c6682731cc5ae8ddde0a9f881e0d29ed2b1f8dL112) is also broken.
It can be fixed by linking to <https://github.com/paritytech/ink/blob/master/integration-tests/e2e-runtime-only-backend/lib.rs> but I think the intention was to copy that test over to the [ink! examples repo](https://github.com/paritytech/ink-examples/)?

**Comment by cmichi** [comment]
@davidsemakula Could you check that there's nothing to be updated for either https://github.com/paritytech/ink/pull/2143 nor https://github.com/paritytech/ink/pull/2140?

**Comment by cmichi** [comment]
> @cmichi Additionally, the example link [here](https://github.com/paritytech/ink-docs/pull/331/files#diff-f108ed3ca9a913da83ecdb04d6c6682731cc5ae8ddde0a9f881e0d29ed2b1f8dL112) is also broken. It can be fixed by linking to https://github.com/paritytech/ink/blob/master/integration-tests/e2e-runtime-only-backend/lib.rs but I think the intention was to copy that test over to the [ink! examples repo](https://github.com/paritytech/ink-examples/)?

Thanks for flagging it! We'll copy the test over. 

The intention behind the copying was that the `ink-examples` contain examples with a source code that fits the last published release, whereas the contracts in `ink/integration-tests` often already have some breaking unreleased changes in `master`.

**Comment by davidsemakula** [comment]
> ... Could you check that there's nothing to be updated for either [paritytech/ink#2143](https://github.com/paritytech/ink/pull/2143) nor [paritytech/ink#2140](https://github.com/paritytech/ink/pull/2140)?

@cmichi confirmed 👍
5.x docs don't use any syntax that's been removed/changed by https://github.com/paritytech/ink/pull/2140, https://github.com/paritytech/ink/pull/2143 or https://github.com/paritytech/ink/pull/2146

**Review by cmichi — APPROVED** [review]

**Pull request merged**
