### PR TITLE
feat: more lambos 🏎️

### PR DESCRIPTION
**Pull request by peetzweg**
https://user-images.githubusercontent.com/839848/229220309-0838d4ca-7d94-4a92-a114-05f8eeecc04c.mov

### CODE REVIEW

**Comment by SkymanOne** [comment]
🏎️

**Review by HCastano — APPROVED** [review]
🏎️

**Comment by HCastano** [comment]
@peetzweg I aped this in without reading into the CI errors, looks like we need to fix them for the release to work. Can you do that in a follow up 😅

**Comment by peetzweg** [comment]
@HCastano 
Seemed like some CI checks failed the deployment in production. My last info was anyways to not release it this year with the traction ink has right now. So all good! :)

Just reverted the changes on master. ✌️

**Pull request merged**
