### PR TITLE
fix: address link-check failure for supercolony

### PR DESCRIPTION
**Pull request by 0xf333**
Outdated links are causing `markdown-link-check` check to fail during pull request checks.

## Description
`Old link`: https://supercolony.net/ (404 webpage) 
`Replaced by`: https://brushfam.io/

## Impact
This PR fixes failure associated with Supercolony link.

### CODE REVIEW

**Review by ascjones — COMMENTED** [review]
I believe Supercolony has become Brushfam now, https://brushfam.io, https://github.com/Brushfam

**Comment by 0xf333** [comment]
> I believe Supercolony has become Brushfam now, https://brushfam.io, https://github.com/Brushfam

Hi @ascjones , thanks for the feedback, it's done.

**Comment by ascjones** [comment]
> > I believe Supercolony has become Brushfam now, https://brushfam.io, https://github.com/Brushfam
> 
> Hi @ascjones , thanks for the feedback, it's done.

I spoke to the Brushfam guys, they said that these two links should remain supercolony, since that organisation does still exist and did the original work referenced. Sorry about that!

**Comment by 0xf333** [comment]
> > > I believe Supercolony has become Brushfam now, https://brushfam.io, https://github.com/Brushfam
> > 
> > 
> > Hi @ascjones , thanks for the feedback, it's done.
> 
> I spoke to the Brushfam guys, they said that these two links should remain supercolony, since that organisation does still exist and did the original work referenced. Sorry about that!

Hi @ascjones,  thanks for the feedback.
Since  `https://supercolony.net` still giving a 404 HTTP response, perhaps we should use `https://github.com/Supercolony-net` instead?
Let me know what you think.

**Comment by ascjones** [comment]
> > > > I believe Supercolony has become Brushfam now, https://brushfam.io, https://github.com/Brushfam
> > > 
> > > 
> > > Hi @ascjones , thanks for the feedback, it's done.
> > 
> > 
> > I spoke to the Brushfam guys, they said that these two links should remain supercolony, since that organisation does still exist and did the original work referenced. Sorry about that!
> 
> Hi @ascjones, thanks for the feedback. Since `https://supercolony.net` still giving a 404 HTTP response, perhaps we should use `https://github.com/Supercolony-net` instead? Let me know what you think.

Yes, just link the github :+1:

**Comment by 0xf333** [comment]
> Yes, just link the github 👍

Thanks for the feedback, it's done.

**Review by cmichi — APPROVED** [review]
Thank you, Chris!

**Pull request merged**
