### PR TITLE
Add an example for user defined structs

### PR DESCRIPTION
**Pull request by mmagician**
show how to implement SpreadLayout for a struct that wraps a bool

### CODE REVIEW

**Comment by mmagician** [comment]
On a side note, isn't there a derive macro that would do this automatically?
If not, I might write one soon 🤔

**Comment by cmichi** [comment]
@mmagician Thanks for the PR! What do you think about mentioning the existing `derive` macro in the text?

**Comment by mmagician** [comment]
Totally, will add later!

**Comment by cmichi** [comment]
@mmagician Could you sign CLA posted by the bot above? I'll merge afterwards.

**Review by cmichi — APPROVED** [review]

**Pull request merged**
